export const AUTO_GET_COOKIES = "AUTO_GET_COOKIES";
export const GET_COOKIES_SUCCESS = "GET_COOKIES_SUCCESS";
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE  = "LOGIN_FAILURE";
export const CLOSE_LOGIN_WINDOW = "CLOSE_LOGIN_WINDOW";
export const REQUEST = "REQUEST";